### ISSUE TITLE
Migrate from Amazon Linux to CentOS

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#11]
Flintrock has thus far been built and tested on the assumption that the cluster nodes will be running Amazon Linux. Since we want to make it possible to support cloud providers other than Amazon, we need to get off Amazon Linux.

CentOS is very similar to Amazon Linux and is the obvious choice for switching. Ubuntu is another possibility but I will not pursue that unless there is some compelling argument for it over CentOS.

Switching to CentOS should mostly involve tweaking the shell scripts that run remotely during cluster launches and testing everything out to make sure everything still works.

**Comment by broxtronix** [comment]
Google compute engine currently supports CentOS 7.1.1503 and CentOS 6.5.  I think the only other strong contender here would be a Debian or Ubuntu linux. My vote would probably be to standardize around CentOS 7, since it remains fairly compatible with Amazon Linux and we may even be able to retain Amazon Linux support, which could be handy for some users.  (I myself as relying right now on Amazon's official GPU computing AMI, which runs Amazon Linux.)

[This](https://aws.amazon.com/marketplace/pp/B00O7WM7QW) seems to be the standard Centos 7 image for EC2.

**Comment by nchammas** [comment]
Flintrock can now launch clusters on both Amazon Linux and CentOS AMIs.

The downside when using CentOS is that the default CentOS AMIs don't have Java installed, so CentOS launch times are a couple of minutes higher than Amazon Linux launch times for the default AMIs. :( We should be able to address this in the future if we brush off the [image build work](https://github.com/nchammas/flintrock/tree/master/image-build) I originally built for spark-ec2 and make it a living feature of Flintrock.

Going forward I will target CentOS during my development and testing so that when Flintrock is ready to [add support for different providers like GCE](https://github.com/nchammas/flintrock/issues/10), we'll be able to do that right away since CentOS is supported across providers. But Flintrock should continue to work against Amazon Linux as well.

**Comment by nchammas** [comment]
I gotta say, after launching many clusters on both Amazon Linux and CentOS, the experience is much faster and better overall with Amazon Linux.

When Flintrock is ready to support a new cloud provider, I think it will be good to revisit the question of what distribution to target. Maybe we can get a better experience on average on both EC2 and, say, GCE with Ubuntu as opposed to CentOS.

For the time being, I will continue making sure Flintrock works on both Amazon Linux and CentOS, but personally, I will be using Amazon Linux for my day to day work.
