### ISSUE TITLE
Add copy-dir command

### ISSUE THREAD

**Issue by sylvinus** [nchammas/flintrock#136]
I think that could be helpful for users in addition to copy-file.

If deemed useful, the implementation could either do an `os.walk()` and call copy-file for each file, or maybe compress, send the archive and uncompress on each node.

**Comment by nchammas** [comment]
You can get this behavior today by doing the zipping and unzipping yourself:

```
zip stuff.zip ...
flintrock copy-file my-cluster stuff.zip
flintrock run-command my-cluster 'unzip stuff.zip'
```

But certainly, it would be handy if Flintrock could do this for you.

I didn't implement this in Flintrock in the first place because I didn't want to do the work when there was a fairly straightforward workaround available, and because Paramiko (the SSH library that Flintrock uses) [doesn't provide machinery to do this out of the box](http://docs.paramiko.org/en/2.0/api/sftp.html#paramiko.sftp_client.SFTPClient.put).

If Flintrock ever manages to switch to AsyncSSH (#9), I am more likely to implement this (or accept contributions that implement it) since AsyncSSH [makes this easy](http://asyncssh.readthedocs.io/en/stable/api.html#asyncssh.SFTPClient.put).

**Comment by nchammas** [comment]
Closing due to the above reasons. I would consider a contribution that implemented `copy-dir` roughly according to the manual workaround I suggested above, but I'm unlikely to tackle this myself.
