### ISSUE TITLE
Issue when using custom Spark URL without Hadoop

### ISSUE THREAD

**Issue by sylvinus** [nchammas/flintrock#139]
I'm using a Spark (2.0) version without Hadoop, with `--spark-download-source`.

I thought that adding HDFS would install Hadoop as well, which it does, but Spark doesn't start because of a classpath issue.

I need to cancel the launch and then run this to make Spark start:
```
flintrock run-command XXX "echo 'export SPARK_DIST_CLASSPATH=\$(hadoop classpath)' >> /home/ec2-user/spark/conf/spark-env.sh"
```

I don't know if there is another proper solution?

Thanks,

**Comment by BenFradet** [comment]
I have faced the same problem in the past and haven't found a "proper" solution either.

**Comment by nchammas** [comment]
> I'm using a Spark (2.0) version without Hadoop

If you install Spark built against Hadoop 2.7 do you still have this issue?

**Comment by sylvinus** [comment]
Not sure what you mean? The `spark-2.0.0-bin-hadoop2.7.tgz` binaries work, but the `spark-2.0.0-bin-without-hadoop.tgz` don't seem to.

**Comment by BenFradet** [comment]
We could do it directly by adding this env var to `spark-env.sh` but we would have to know that hdfs has been installed.

**Comment by sylvinus** [comment]
as it's a shell script, maybe we can test for that directly inside `spark-env.sh` ?

**Comment by BenFradet** [comment]
Yup, we could.

**Comment by nchammas** [comment]
> Not sure what you mean? The spark-2.0.0-bin-hadoop2.7.tgz binaries work, but the spark-2.0.0-bin-without-hadoop.tgz don't seem to.

That's exactly what I mean. `spark-2.0.0-bin-hadoop2.7.tgz` is Spark built against Hadoop 2.7.

So my next question is: If that works, why do we care about the version of Spark without Hadoop?

I've never used it, so I confess I don't know what it's good for.

**Comment by sylvinus** [comment]
@nchammas I'm using a version I built from source without Hadoop included because that seemed unnecessary.

**Comment by nchammas** [comment]
I think there is some misunderstanding about what `spark-2.0.0-bin-hadoop2.7.tgz` means.

It means that Spark was built against Hadoop 2.7, not that Hadoop 2.7 itself is included in the distribution.

You need to build Spark against different versions of Hadoop because the Hadoop project is quite bad about maintaining backwards compatibility. To use Spark with a certain version of Hadoop, you need to build certain parts of Spark to target the correct version of the Hadoop API. Hence, we have Spark built against multiple versions of Hadoop. You still need to download and install Hadoop separately to get the actual Hadoop software, if you actually want to use it.

I think you would only want to use `spark-2.0.0-bin-without-hadoop.tgz` when you want to target some non-standard version of Hadoop. I'm not sure why else you would want to use it.

Does that clarify things? Do you still have a reason to use `spark-2.0.0-bin-without-hadoop.tgz`?

**Comment by sylvinus** [comment]
Ah ok got it. Thanks for the explanation, I think I was confused by the fact that the tgz is 70MB larger and includes `hadoop-common-2.7.2.jar` for instance.

**Comment by nchammas** [comment]
I'm not that familiar with Java, but I believe that `hadoop-common` JAR is how Spark links against the appropriate version of the Hadoop API. It's not the actual Hadoop application.

**Comment by sylvinus** [comment]
OK! Well, all very confusing but thanks again for the help!

**Comment by nchammas** [comment]
Yeah, it is quite convoluted. 😕 

@BenFradet - Were you also using the `without-hadoop` build? You mentioned running into similar issues as @sylvinus.

**Comment by BenFradet** [comment]
Yes, we had the same thing internally but we have requirements not to use the built against hadoop vX.X Spark (I don't know what those are tbh).
