### ISSUE TITLE
No log/debug info to figure out hangup clusters

### ISSUE THREAD

**Issue by douglaz** [nchammas/flintrock#177]
* Flintrock version: latest master
* Python version: 3.4.3
* OS: Ubuntu

I tried starting a big cluster a couple of times and I get stuck like this:
```
Requesting 100 spot instances at a max price of $0.04...
0 of 100 instances granted. Waiting...
All 100 instances granted.
```
The machines seem okay but nothing happens. For small clusters it works, although sometimes it takes a long time.

My experience with spark-ec2 shows that this kind of situation is frequently explainable by some machine with a network/ssh problem. spark-ec2 will generally show some info in this case, but here I get no clue of what is happening.

I intend to add a --verbose/--debug flag to make the script more talkative overall. I'm trying to make this script production-ready and the ability to figure out what is happening is vital.

**Comment by nchammas** [comment]
As far as a general verbose mode is concerned, this issue looks like a dup of #47.

Otherwise, if there is a specific failure mode that you've identified, let's figure out exactly what it is and target that specifically if possible. For example, if a host is taking a long time to become SSH-ready, perhaps we can display a warning in [`get_ssh_client()`](https://github.com/nchammas/flintrock/blob/master/flintrock/ssh.py#L46)?

**Comment by pragnesh** [comment]
i also seen these issue. by looking at all instance i found that sometimes It takes to much of time to downloading hadoop from some apache mirror.

**Comment by nchammas** [comment]
@pragnesh - You can set your download source for HDFS to a specific mirror that runs fast using `--hdfs-download-source` (or the equivalent in your Flintrock config file). By default, Flintrock will download HDFS from a different mirror on each node to spread the load, and sometimes one of those mirrors will be really slow.

**Comment by douglaz** [comment]
@pragnesh @nchammas I have saved a spark package in s3 and it downloads without noticeable slowdowns. I will do the same for hdfs because sometimes it takes 5 minutes for a machine to download the package.

**Comment by nchammas** [comment]
Yes, that's the purpose of the `download-source` options, to let you download from any location as it suits your needs. Have you had issues with downloading Spark, though?

Flintrock already downloads Spark from S3, since Databricks hosts Spark releases there. Unfortunately, no-one does the same for Hadoop, which is why we have to deal with Apache mirrors when downloading Hadoop.

**Comment by douglaz** [comment]
@nchammas, in fact, I've never tried it. Since the beginning, I'm testing with my own s3 package because it has a patch to upgrade a library that causes deadlocks in Jackson (it causes the executor's JVM to hang up). So I don't know if the standard path is good enough.
By the way, I did some tests today with the s3 HDFS package and it runs very smoothly. Only now I'm really impressed with flintrock's speed. The standard download path obscures flintrock's capabilities.

**Comment by nchammas** [comment]
> The standard download path obscures flintrock's capabilities.

Thanks for pointing that out. I would like to figure out at some point a way to fix this without having to host Hadoop releases on S3 myself. In the past we've discussed approaches like having an Apache mirror blacklist, but it didn't seem like a good solution.
