### ISSUE TITLE
Ubuntu Support & user configurable wait/sleep time

### ISSUE THREAD

**Issue by pani6me** [nchammas/flintrock#222]
Thank you for a great product. 

* Flintrock version: latest from git pull
* Python version: 3.6
* OS: ubuntu

Tried launching clusters (ubuntu AMI) failed launches many times. So upon investigation into the code these were the bottle-necks:
1. waiting to ssh to clusters (3 secs is way too less.) Can it be given from command/config? 
2. It assumes that python already exists to download hadoop. Won't work if python does not exist. Could you please allow user given set of command we can pre-execute for dependencies. 
3. assumes "yum install/remove"  can we make this user-driven optionally (to support apt install/remove)

still ran into issues for java based dependencies in ubuntu, so I dropped that route. But for Amazon linux at least user-driven wait-time and number of tries would be helpful. 

thank you
Deb

**Comment by nchammas** [comment]
Hi @pani6me!

1. Can you elaborate on what the issue is here? Flintrock polls for SSH availability every few seconds so it can start work as soon as possible. I don't understand what the problem is or why someone would want to control the polling interval.
2. Flintrock works best with Amazon Linux, but if you want to use an AMI that doesn't have Python installed by default, you can install Python as part of instance launch using the `--ec2-user-data` option.
3. Ubuntu support is tracked in #95. [My comment there](https://github.com/nchammas/flintrock/issues/95#issuecomment-197924531) still captures my attitude towards Ubuntu: I'd support it if it didn't add much complexity or maintenance burden. But I doubt that is possible, which is why my default position is [not to expand Flintrock's support matrix](https://github.com/nchammas/flintrock/blob/20c7e42a8b8c60ca4e8cd6cef15ba2e2cb7028fc/CONTRIBUTING.md#dont-expand-the-support-matrix).

**Comment by pani6me** [comment]
Thanks for the info @nchammas 
1. No longer an issue when I used amz-linux.
2. I agree supporting ubuntu would be a constant support overhead, especially custom built AMIs.  --ec2-user-data is a great concept. If you could extend the concept of --ec2-user-data to include the install file for master and slave separately, then that would give the responsibility/power on the users to specify the correct commands for any linux system. I'll probably make this temporary hack for my use in local area. Then flintrock can put the installation logs for master and slave in some tmp area without reading into the logs/runs success/failure.
3. If above options for master/slave are available ubuntu support may not be needed.

**Comment by nchammas** [comment]
I've reported #223 to capture the feature request for separate `--ec2-user-data` options.
