### ISSUE TITLE
Improve root volume setup and add some EBS volume support

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#28]
There are probably a few things that need to be done here which need to be fleshed out, including:
- [ ] Tuning the size or type of the root volume (magnetic vs. SSD; ext4 setup; etc.)
- [ ] Configuring additional EBS volumes (persistent storage)
- [ ] Configuring additional instance store volumes (ephemeral storage); good as scratch space
- [ ] Picking good defaults for this stuff
- [ ] Deciding on how much of it should be configurable

**Comment by broxtronix** [comment]
I have been needing a larger root drive on my instances (10GB is not nearly enough!!), and have added the capability to choose the EBS size and type for the root drive.  As a nice fringe benefit, EBS volumes backed by SSD drives (type "gp2") are much more performant than the magnetic drive-backed EBS volumes.  With an SSD root drive, instances boot and install software much quicker.  These SSD-backed EBS volumes only cost twice as much as magnetic-backed EBS, which is well worth the cost in my opinion.  I think a 20 GB gp2 drive would be a sensible default for the root partition.

Here is the code snippet that creates a root drive (of a certain size and type).  On my Amazon Linux AMI, the root drive was automatically resized to take advantage of all of the available space allotted to it on the underlying block store.  I suspect this happens on CentOS AMIs as well.

```
           # Configure instance root drive. Note that if you choose a size
           # larger than 10GB, you may need to resize the filesystem once your
           # instance is running, using resize2fs, although some AMIs do this automatically.
           from boto.ec2.blockdevicemapping import BlockDeviceMapping, BlockDeviceType, EBSBlockDeviceType
           block_map = BlockDeviceMapping()
           device = EBSBlockDeviceType()
           device.size = int(ebs_root_vol_size)   # size in GB
           device.volume_type = ebs_root_vol_type # [ standard | gp2 | io1 ]
           device.delete_on_termination = True
           block_map["/dev/xvda"] = device

           reservation = connection.run_instances(
               image_id=ami,
               min_count=(num_slaves + 1),
               max_count=(num_slaves + 1),
               key_name=key_name,
               instance_type=instance_type,
               placement=availability_zone,
               security_group_ids=[sg.id for sg in security_groups],
               subnet_id=subnet_id,
               placement_group=placement_group,
               tenancy=tenancy,
               block_device_map=block_map,
               ebs_optimized=ebs_optimized,
               instance_initiated_shutdown_behavior=instance_initiated_shutdown_behavior)
```

**Comment by ericmjonas** [comment]
I'm running up a slightly-different version of this problem -- I really want spark to be able to use the ephemeral storage for hdfs, but it seems for r3.8xlarge instances you have to manually specify the ephemeral block device mapping on start-up. Akin to the ec2-ami-list.yaml, could we add in information about the default ephemeral stores available for each instance type, and attach them through the block device mapper? 

It seems like everything except for ebs root and ephemeral storage can be configured once the instances are up.

**Comment by ericmjonas** [comment]
Following up on my previous comment, this appears to be a known problem. From `spark_ec2.py`, 

```
    # AWS ignores the AMI-specified block device mapping for M3 (see SPARK-3342).
    if opts.instance_type.startswith('m3.'):
        for i in range(get_num_disks(opts.instance_type)):
            dev = BlockDeviceType()
            dev.ephemeral_name = 'ephemeral%d' % i
            # The first ephemeral drive is /dev/sdb.
            name = '/dev/sd' + string.letters[i + 1]
            block_map[name] = dev
```
[SPARK-3342](https://issues.apache.org/jira/browse/SPARK-3342)

**Comment by nchammas** [comment]
Hey @ericmjonas, you're talking about adding additional instance store volumes and not changing the root volume, right?

Just for the record, to switch between instance store and EBS for the root volume, you need to switch AMIs. Additionally, Amazon [recommends](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/RootDeviceStorage.html) EBS root volumes because they launch [faster](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ComponentsAMIs.html#storage-for-the-root-device).

If we're talking about adding additional, instance store-backed volumes, that seems reasonable to me. Could you elaborate on why you prefer them over having the option to add additional EBS-backed volumes?

I know spark-ec2 launches clusters with an `ephemeral-hdfs` and `persistent-hdfs`. Is this related to that idea? An area that Spark can use for `SPARK_LOCAL_DIRS`, large shuffles and the like?

**Comment by ericmjonas** [comment]
@nchammas I had been talking about using the physical on-the-instance "ephemeral storage" -- it turns out the M3 type we use most often doesn't by-default make these available to the host OS. Many (most?) of the instance types provide this local storage and it works really well for ephemeral-hdfs and other temporary storage, and (unlike the EBS volumes) doesn't require us to hit the network. 

This seems like a bug on AWS's side but they ... at least document it? ""For M3 instances, you must specify instance store volumes in the block device mapping for the instance. When you launch an M3 instance, we ignore any instance store volumes specified in the block device mapping for the AMI.""

**Comment by nchammas** [comment]
Yup, [instance store](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) is AWS lingo for their ephemeral storage.

OK, so we do want this for use as scratch space. I'll update the issue description accordingly.

**Comment by ericmjonas** [comment]
@nchammas I've been thinking about trying to make a bit of progress on this front, and wanted feedback before I really dive in. The official behavior here is complex, esp w.r.t supporting arbitrary AMIs:

1. it seems like any AMI can specify a default block device mapping. We can override this when we launch an instance, but for some AMIs this might break things. 
2. Many AWS-optimized amis, such as the official AMI from amazon, don't have any block device mapping besides the root volume. So If you want to be able to touch the ephemeral disks, you need to manually map them at start.
3. This requires that you understand which of ephemeral0-ephemeral20 is present at lauch for a particular instance type. Thus we'll need to keep some additional per-instance-type metadata around. 
4. I haven't confirmed but @shivaram in the amplab told me "SSDs don’t get formatted but the hard disks get formatted automatically". So that's a fun additional wrinkle. 

One possible solution is: 

1. query the AMI to see what its block device situation is
2. for the ephemeral drives that it's not using, mount them at some canonical points, format them, and use them for ephemeral hdfs
3. Make it so this can be customized if people really want to.

**Comment by nchammas** [comment]
> query the AMI to see what its block device situation is

Query the AMI, or did you mean query the instance type?

Anyway, I think there's a lot to think about here and it's easy to get sucked in to all details. I'm worried about adding too much complexity without getting enough return in the long run.

Let me ask this, for starters: As a user, what's the *absolute minimum* level of disk setup that would make Flintrock useful to you? What kind of setup are you really going to use, 90% of the time? I think that would be a good starting point for a discussion.

spark-ec2 does [maintain](https://github.com/apache/spark/blob/07ced43424447699e47106de9ca2fa714756bdeb/ec2/spark_ec2.py#L952) a mapping of local volumes available by instance type, copied from [Amazon's docs](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html). I wonder if there's an elegant way around having to do that ourselves.

**Comment by ericmjonas** [comment]
Sorry, I meant query the ami:
```
import boto.ec2

conn = boto.ec2.connect_to_region('us-west-2')
#test_ami ='ami-9ff7e8af'
test_ami = 'ami-bb46558b'



def get_ami_ephemeral_mounts(conn, ami):
    img = conn.get_image(test_ami)

    mp = {}
    for mount_point, device in img.block_device_mapping.items():
        mp[device.ephemeral_name] = mount_point
    return mp

print( get_ami_ephemeral_mounts(conn, test_ami))
```

For the case with `ami-9ff7e8af`
```
(py3k)dhcp-47-226:keystone jonas$ python testami.py
{None: '/dev/xvda'}
```

and with `ami-bb46558b`
```
(py3k)dhcp-47-226:keystone jonas$ python testami.py
{'ephemeral14': '/dev/sdp', 'ephemeral3': '/dev/sde', 'ephemeral5': '/dev/sdg', 'ephemeral4': '/dev/sdf', 'ephemeral15': '/dev/sdq', 'ephemeral10': '/dev/sdl', 'ephemeral1': '/dev/sdc', 'ephemeral13': '/dev/sdo', 'ephemeral8': '/dev/sdj', 'ephemeral12': '/dev/sdn', None: '/dev/sda1', 'ephemeral2': '/dev/sdd', 'ephemeral11': '/dev/sdm', 'ephemeral0': '/dev/sdb', 'ephemeral9': '/dev/sdk', 'ephemeral7': '/dev/sdi', 'ephemeral6': '/dev/sdh'}
```



I think "what's the absolute minimum level of disk setup that would make Flintrock useful to you? What kind of setup are you really going to use, 90% of the time?" is 100% the right attitude! The minimum I need is for flintrock to put the instance storage in the block-device-mapping, otherwise I can't do anything with the ephemeral storage after the instance is up. 

Attaching additional EBS block devices, etc. are all things I can do after. I could even install and deploy HDFS later, although I think that also comes in the "what I'm going to use 90% of the time" column.

**Comment by nchammas** [comment]
> The minimum I need is for flintrock to put the instance storage in the block-device-mapping, otherwise I can't do anything with the ephemeral storage after the instance is up.

So to lay it out again like you did earlier, the minimum we want to start with is:

1. Query the AMI for mount points.
2. If any are not assigned names, that means they need to be manually formatted on launch. Do that.

Did I get that right?

> Attaching additional EBS block devices, etc. are all things I can do after. I could even install and deploy HDFS later, although I think that also comes in the "what I'm going to use 90% of the time" column.

Yup, I favor leaving this stuff for later if possible. You might be able to do the HDFS setup for now using `run-command`, but if not we'll look at adding it in. Is Spark usable for your use cases with local storage but without HDFS?

By the way, about something you mentioned earlier:

> This seems like a bug on AWS's side but they ... at least document it? ""For M3 instances, you must specify instance store volumes in the block device mapping for the instance. When you launch an M3 instance, we ignore any instance store volumes specified in the block device mapping for the AMI.""

I took a look at this, and it looks like Amazon [updated their docs](https://issues.apache.org/jira/browse/SPARK-3342?focusedCommentId=14974660&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14974660) to remove special mention of M3 instances. So perhaps they fixed this irregularity.

**Comment by broxtronix** [comment]
To add another data point:

My "absolute minimum" list would be:

1. Making sure that ephemeral [instance store](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) disks are in the block device map, and making sure they are formatted and mounted when the instance boots up.  I use these frequently as scratch space.
2. Being able to (optionally) resize the root device to be bigger than the standard 10GB of most AMIs.  

And although it is not strictly necessary, I think it would be very nice to be able to specify the storage type of the root device so that I could leverage faster SSD-backed root drives when desired, as these speed up the responsiveness of the cluster considerably.  This is basically a freebie that goes along with (2) above, since it is just a one-line tweak to the block device map.

If Flintrock does attempt to support 3rd party AMIs, then the issue of mapping AMI block device maps does become complicated, as they may differ from the instance block device map.  This is simplified quite a bit if Flintrock only supports a standard CentOS image, in which case the instance block mapping is the only one potentially in need of configuration.

Just out of curiosity, @ericmjonas , do you and your colleagues at the amplab rely heavily on your own customized AMIs?  Or do you get by ok with a "vanilla" AMI like the Amazon Linux that `spark-ec2` uses?

**Comment by nchammas** [comment]
> 2. Being able to (optionally) resize the root device to be bigger than the standard 10GB of most AMIs.

This is a good one. I would favor just picking a larger size (I believe you mentioned 20GB earlier) and hardcoding it in.

> And although it is not strictly necessary, I think it would be very nice to be able to specify the storage type of the root device so that I could leverage faster SSD-backed root drives when desired, as these speed up the responsiveness of the cluster considerably. This is basically a freebie that goes along with (2) above, since it is just a one-line tweak to the block device map.

Same here. If SSDs are generally better, I would favor just baking that configuration in.

> If Flintrock does attempt to support 3rd party AMIs, then the issue of mapping AMI block device maps does become complicated, as they may differ from the instance block device map. This is simplified quite a bit if Flintrock only supports a standard CentOS image, in which case the instance block mapping is the only one potentially in need of configuration.

I'd rather have Flintrock focus on 1 type of AMI, like the base CentOS AMI. If people want to try others, they're on their own. We should try not to make that intentionally difficult, but I wouldn't go out of my way to accommodate people using their own stuff either.

There's a small chance that, down the line, we can revive the [image-build](https://github.com/nchammas/flintrock/tree/master/image-build) scripts and maintain a set of Flintrock AMIs. But that's way in the future.

**Comment by ericmjonas** [comment]
@nchammas  you're to pick an AMI and keep it up to date / peg to a common one (like the AWS-supplied one) that would simplify a LOT of work. For some reason I thought that AMI-neutrality was a design goal. 

@broxtronix As I understand it spark_ec2 points to a variety of lightly-customized but often-outdated AMIs (because who has time to build new ones and deploy to all availability regions?) This leads to things being out of date and a real problem when we're trying to use non-java software (I use spark-python with an anaconda-based python that often then calls out to custom C++ -- stale AMIs make my life hell) 

I'd like to +1 @nchammas suggestion to just support SSDs with 20GB initial root partitions at the moment. Other than cost, are there any downsides?

**Comment by ericmjonas** [comment]
I'm really excited by the flintrock model of "by default we use the latest of everything, although via config file you can peg to an older version if you need to"

**Comment by nchammas** [comment]
> For some reason I thought that AMI-neutrality was a design goal.

@ericmjonas Can you elaborate on what you mean?

For starters I'm testing Flintrock against the official, base CentOS AMI. To a lesser extent, I also test against the official, base Amazon Linux AMI, since CentOS and Amazon Linux are so similar.

I think it makes sense to do this because CentOS is available on other providers as well (e.g. GCE, which Flintrock may support in the future), and we don't run the burden of having to maintain our own AMIs like spark-ec2. Supporting other distributions like Ubuntu means we have to change our setup scripts accordingly and increases our testing surface area, which I'm against for now.

There is a related discussion in #11 you might be interested in.

> As I understand it spark_ec2 points to a variety of lightly-customized but often-outdated AMIs (because who has time to build new ones and deploy to all availability regions?) This leads to things being out of date

Just a side-comment on this: I did a whole bunch of work to fix this for spark-ec2 in [SPARK-3821](https://issues.apache.org/jira/browse/SPARK-3821) by automating the process of updating its AMIs. I've imported that work here under [image-build](https://github.com/nchammas/flintrock/tree/master/image-build).

It never made it into spark-ec2 because I couldn't get a committer to shepherd it through, but we *may* opt to revive it for use with Flintrock. I would rather avoid that, honestly, but it's an option.

> I'd like to +1 @nchammas suggestion to just support SSDs with 20GB initial root partitions at the moment. Other than cost, are there any downsides?

Don't think so. And is the cost difference large enough to matter to users? Does it matter to either of y'all?

> I'm really excited by the flintrock model of "by default we use the latest of everything, although via config file you can peg to an older version if you need to"

This stems from my general fear of being bogged down supporting older versions of stuff over the long term. Latest is what we support. You can reach into the past, but the further back you reach the more on your own you are. :)

**Comment by ericmjonas** [comment]
> @ericmjonas Can you elaborate on what you mean?

I guess I assumed that, because there wasn't an official flintrock AMI, the goal was to support all possible AMIs. Now that I know that's not the case, it makes life so much easier! 

> Don't think so. And is the cost difference large enough to matter to users? Does it matter to either of y'all?

Not to me or anyone at AMPLab, and we're at a pretty big scale (although we don't keep large clusters up for a long time -- so maybe for those users it might matter more. Not sure).

**Comment by broxtronix** [comment]
The [cost difference](https://aws.amazon.com/ebs/pricing/) is pretty minimal.  Magnetic storage is $0.05 / GB-month, and SSD storage is $0.10 / GB-month.  These costs are tiny in comparison to the cost of the instances themselves.  I don't think users of smaller clusters would even notice the difference too much.

Regarding the block device maps, it sounds based on this discussion like there will not be a need to support arbitrary AMI block device maps (thank goodness, as that sounds like a Sisyphean task!).  

However, as a user I would still hope to be able to use any ephemeral [instance store](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) disks that are bundled with the instance.  My understanding is that these must be configured as part of the block store at instance launch time, so they cannot be attached by the user at a later point as part of their own custom configuration.  Since these instance store disks often form the ephemeral storage substrate for network filesystems like Hadoop, I suspect it'll be a commonly requested feature.  I use it in my clusters for both Hadoop and for temporary working directories for my pyspark processes, and would consider it to be one of the necessary features to really be able to use flintrock day-to-day.  

Unfortunately it does not look to me like there is any way to query for a "default" block store that would include these local instance store disks... although perhaps one of you may find something in boto that I overlooked.  An automated way to set up the appropriate "default" block store for a given instance type would be ideal, but it sounds like people generally configure these manually.  I think a lookup table, as was done in `spark-ec2`, may be the only way to implement this feature, but I'm curious if either of you have another take on how this might be implemented in a way that minimizes maintenance down the road.

**Comment by nchammas** [comment]
> I guess I assumed that, because there wasn't an official flintrock AMI, the goal was to support all possible AMIs.

I'll probably add a note to the README explaining that we target and support CentOS, though users are free to try other distributions.

>  An automated way to set up the appropriate "default" block store for a given instance type would be ideal, but it sounds like people generally configure these manually. I think a lookup table, as was done in spark-ec2, may be the only way to implement this feature, but I'm curious if either of you have another take on how this might be implemented in a way that minimizes maintenance down the road.

I'm looking at [how spark-ec2 uses this table](https://github.com/apache/spark/blob/4bb2b3698ffed58cc5159db36f8b11573ad26b23/ec2/spark_ec2.py#L1027-L1038) and I'm a little confused. :confused: 

What is the relationship between the instance type-specific information in [this table](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html#instance-store-volumes) and the AMI-linked mount point information [Eric mentioned earlier](https://github.com/nchammas/flintrock/issues/28#issuecomment-151165647)?

**Comment by ericmjonas** [comment]
> What is the relationship between the instance type-specific information in this table and the AMI-linked mount point information Eric mentioned earlier?

I have been thinking of it as the following: 

1. Each physical instance type has some number of ephemeral devices that physically sit in the box. 
2. the block device mapping has the hypervisor "virtually connect" those devices to the guest OS / ami. If the hypervisor doesn't connect (attach) them, the AMI will never see them
3. an AMI can contain metadata telling the hypervisor to attach these devices. before the hypervisor launches an ami as a guest, it can attach things as the AMI requests. AMIs don't always have the metadata to make this request, because (say) a particular AMI wants to run on as many instance types as possible. 
4. Somewhere the metadata "c3.8xlarge has two ephemeral SSD disks" has to be tracked so that a script (like spark EC2) knows which ephemeral devices to request the hypervisor attach.

**Comment by shivaram** [comment]
My two cents:

1. While creating the AMI you can add as many mappings as you want. So while creating the Spark EC2 AMIs I think we just adding 4 mappings
2. From what I know, if the instance only has one disk and finds 4 mappings EC2 just satisfies the first few mappings.
3. So from the point of view of spark-ec2 the mappings already exist when the instance is launched and the things it does after that are:
  - Formatting the drives if they are SSDs 
  - Creating HDFS data dirs, Spark local dirs and setting them in the config (This is what the mapping is actually used for)

From flintrock's perspective I guess you need to figure out if you assume the AMI has the right mappings or if you want to add it during launch

**Comment by broxtronix** [comment]
> What is the relationship between the instance type-specific information in this table and the AMI-linked mount point information Eric mentioned earlier?

I am not certain, but I believe that the AMI block map includes any EBS volumes that happen to be attached to an instance when it is frozen and an AMI is created.  This can include mappings to local "ephemeral" [instance store](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/InstanceStorage.html) disks as well as other EBS-backed volumes that may have been mapped and attached to an instance.  

I think we are aiming here to just support the ephemeral instance storage disks that are listed in this link.  These are actual disks that are attached to the host on which the instance is running, and are intended as local scratch space.

I really like the suggestion made by @shivaram, where we would simply create 4 mappings and leave it to Amazon to fulfill as many of those mappings as it can, subject to the number of disks available on an instance.  I tried that out this morning, using the following block of code:

```
            # Configure instance root drive. Note that if you choose a size
            # larger than 10GB, you may need to resize the filesystem once your
            # instance is running, using resize2fs, although some AMIs do this automatically.
            from boto.ec2.blockdevicemapping import BlockDeviceMapping, BlockDeviceType, EBSBlockDeviceType
            block_map = BlockDeviceMapping()
            device = EBSBlockDeviceType()
            device.size = int(ebs_root_vol_size)   # size in GB
            device.volume_type = ebs_root_vol_type # [ standard | gp2 | io1 ]
            device.delete_on_termination = True
            block_map["/dev/xvda"] = device

            # The first ephemeral drive is /dev/xvdb
            emphemeral_names = [ '/dev/xvdb', '/dev/xvdc', '/dev/xvdd', '/dev/xvde' ]
            for i in range(4):
                device = BlockDeviceType()
                device.ephemeral_name = 'ephemeral%d' % i
                block_map[ emphemeral_names[i] ] = device

```

This worked, inasmuch as it made two ephemeral instance store SSD disks available on my g2.8xlarge instance.  Oddly, one of these was formatted and mounted automatically, while the other was formatted but not mounted.  I'm using a version of Amazon Linux that supports GPUs, so maybe this is a bug in this particular AMI.  We should try it with the CentOS image that Flintrock is intending to standardize on to see how this works.  

For future reference, the `lsblk` command is useful for debugging which block devices are available on your instance once it boots up.  Here is the output of `lsblk` on my instance after running the above code:

```
[ec2-user@ip-10-33-165-245 ~]$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0  100G  0 disk 
└─xvda1 202:1    0  100G  0 part /
xvdb    202:16   0  130G  0 disk /media/ephemeral0
xvdc    202:32   0  130G  0 disk 
```
You can see from this output that `xvdb` was formatted and mounted, and `xvdc` was not mounted.  (Turns out it was formatted... I was able to mount it with `sudo mount /dev/xvdc /media/ephemeral1`)

I believe that something very much like the code above will mostly address the needs being discussed here.  We may need to mount an additional stray disk or two manually once the cluster is up and running, but other than that this seems to work.

**Comment by ericmjonas** [comment]
+1 @broxtronix 's solution -- it seems easy and a good intermediate point. My understanding is one of the major benefits of the amazon-linux amis is they handle a lot of the formatting for you, but I don't know if we should depend on that.

**Comment by ericmjonas** [comment]
@broxtronix Are you ok with me starting to hack on this as a PR? I'm basically going to copy your approach but I wanted to make sure I wasn't stepping on any toes. I'm blocked on both this and HDFS deployment.

**Comment by broxtronix** [comment]
Of course, @ericmjonas !!   I will gladly follow along and help review the PR!   Have at it. :)

**Comment by ericmjonas** [comment]
@broxtronix the Amazon centos-based AMIs resize the root partition automatically, but it appears the "Centos 7 with updates" AMIs do not. Do you know of an easy way to do this? resize2fs seems to need me to manually muck with the partition table first and i'm curious if there's an easier way. I've googled around to little avail, with a lot of advice from 2009 that seems less than applicable today.

**Comment by broxtronix** [comment]
Hmmm, it's too bad that the Centos 7 AMI doesn't doesn't grow the root partition automatically.  To do this manually, I think there are basically two steps involved:

1. Rewriting the partition table so that the partition uses all available space on the block device. 
2. Resizing the filesystem to use all available space on the partition.

[This post](http://blog.backslasher.net/growroot-centos.html) delves into more details about how this is done with the Centos AMI in particular.  They use the `growroot.sh` script to automatically resize partitions and resize the filesystem in one go.  They are pretty simple to use... they recommend trying:

```
yum update -y
yum install -y epel-release
yum install -y perl cloud-init dracut-modules-growroot
rpm -qa kernel | perl -pe 's/^kernel-//'  | xargs -I {} dracut -f /boot/initramfs-{}.img {}
<reboot instance>
```

I used this script that performs a very similar set of steps to [resize the root partition on GCE instances](https://github.com/broxtronix/spark-gce/blob/master/spark_gce/support_files/growroot.sh).  I would try running these commands by hand first, and if it works we could figure out how to incorporate it into the launch process for new instances. 

Let me know if this helps!

**Comment by nchammas** [comment]
Is anyone actively working (or intending to work) on this issue? If not, I can take it on now that I finished work on adding [HDFS support](https://github.com/nchammas/flintrock/issues/41) to Flintrock.

**Comment by ericmjonas** [comment]
I started but then got totally slammed by a friday conference deadline :(
All I had really done is stolen Michael's code and put it in the right spot
-- if we're focusing on the Amazon AMI it's even easier because the root
partition resizing is handled automatically.

**Comment by broxtronix** [comment]
I am not actively working on this either, but would be glad to give advice & PR feedback if it is helpful!

**Comment by nchammas** [comment]
@ericmjonas:

> if we're focusing on the Amazon AMI it's even easier because the root
partition resizing is handled automatically.

Yeah, I was thinking about the notes earlier on CentOS not resizing volumes automatically. Part of the work we'll need to do here is provider-specific (e.g. creating and attaching EBS volumes), but part of it is tied to the distribution we use.

If we support GCE as an alternate provider down the line, will we end up having to implement this manual resizing stuff anyway? If so, it might be good to get this out of the way now.

For what it's worth, I'm open to revisiting [what distribution to support](https://github.com/nchammas/flintrock/issues/11#issuecomment-154886283) (e.g. maybe Ubuntu can offer us the convenience of Amazon Linux without tying us to an EC2-specific approach), but I think a better time to do that would be when we are ready to add a new provider like GCE.

Anyway, I can work on something else in the meantime. Just let us know if you get too busy with other stuff and someone else can step in.

@broxtronix:

> I am not actively working on this either, but would be glad to give advice & PR feedback if it is helpful!

Advice and PR feedback is absolutely helpful. Please feel free to chime in regardless of who is working on an issue. :+1:

**Comment by ericmjonas** [comment]
Oh I'm sorry Nick, i was trying to suggest that I am _not_ actively working
on it and haven't made any reasonable progress anyway, having merely copied
(and tested) the block of code that @broxtronix had added. Go ahead and
work on it! :)

**Comment by nchammas** [comment]
Oh, word. OK, I'll go ahead and start on this then!

Like with adding HDFS support, I'll open a PR early on so y'all can provide feedback as I work on this feature.
