### ISSUE TITLE
Flesh out Flintrock library interface

### ISSUE THREAD

**Issue by ericmjonas** [nchammas/flintrock#29]
I love flintrock and here in the @amplab we're evaluating it as a replacement for the standard spark ec2 scripts. Are there any plans to make it available as a library? I'd love to be able to 

```
import flintrock
fc = flintrock.clutser("fooconfig.yaml")
fc.get_master()
fc.get_slaves()
```

etc for integration into fabric (http://www.fabfile.org/ )  scripts, which we're starting to use extensively to automate devops things.

**Comment by nchammas** [comment]
Hi Eric! I'm excited that the AMPLab is interested in Flintrock!

Yes, there are definitely plans to flesh out Flintrock's [library story](https://github.com/nchammas/flintrock/tree/c5666fcef8846cb2c1f08647f0a35967b74ba55b#library-use). My focus is first on maturing the command-line interface and cleaning up internals (like in #6) before turning to that. That will take some time.

Until then, I've tried even with the command-line interface to make accommodations for programmatic use. Many commands output information in YAML, which is both human- and machine-readable. It still needs some work, but that's the direction I'm headed in.

When Flintrock becomes ready for library use, it will require Python 3.4+.

I know that this requirement will be an obstacle for potential library users, even though it's a [relief](https://github.com/nchammas/flintrock/blob/c5666fcef8846cb2c1f08647f0a35967b74ba55b/CONTRIBUTING.md#expanding-the-support-matrix) for the project maintainers. So the idea behind printing output in YAML is to enable programmatic use of Flintrock even for people not using Python 3.4+, or even Python at all. You simply call Flintrock as a regular command-line application and then parse its output to get the information you need (cluster status, master address, etc).

What do you think of this direction?

**Comment by ericmjonas** [comment]
Spitting out YAML is a great option, thank you so much!

**Comment by nchammas** [comment]
Sounds good. The YAML output still needs some work, so if you see places that need improvement definitely flag them!

I'm going to reopen this issue, by the way, to track the long-term plan of allowing Flintrock to be used as a Python library.

**Comment by nchammas** [comment]
After a lot of thought, I've decided to indefinitely postpone any plans to make Flintrock usable as a library.

This is what Flintrock will shoot for:
* Provide a great command-line interface and overall user experience.
* When suitable, return output as YAML so that it can easily be consumed programmatically without sacrificing readability.

Not trying to double as a library will simplify future development and, combined with the release of stand-alone packages, will better enable us to use the latest and greatest that Python has to offer without having to worry about library users.
