### ISSUE TITLE
Support for spot instances

### ISSUE THREAD

**Issue by ericmjonas** [nchammas/flintrock#30]
In the todo at the top of the flintrock script, we see:
```   
* Support for spot instances.
        - Show wait reason (capcity oversubscribed, price too low, etc.).
```

Currently it seems like a lot of the machinery for spot instances is in place, including threading the requested spot price through to `launch_ec2`. Would you accept a PR that actually made this live? the spark_ec2.py way is to launch the root node as non-spot and the workers as spot instances -- would this work for a first version?

**Comment by nchammas** [comment]
I would definitely accept a PR that implemented support for spot instances, but there are a few things that need to be figured out.

I'm not sure I want to follow spark-ec2's model of having the master be an on-demand instance and the slaves be spot instances.

I understand the attraction of that approach is that you can persist your setup files and stuff on the master across cluster stop/start cycles and across different sets of spot slaves.

The problem with going that route in Flintrock, at least for now, is that we don't have support for `./flintrock launch ... --resume` like spark-ec2, which allows you to reuse an existing master and launch new slaves. We won't be able to work on that, in turn, until we implement support for some kind of Flintrock manifest that describes a cluster configuration and probably lives on the master.

We need that because we want Flintrock to be able to automatically detect how it should configure the slaves it's adding. What modules should it install? What configuration should each of those modules have? Support for adding regular, on-demand slaves to an existing cluster (#16) also depends on this capability.

An easier way to add support for spot instances to Flintrock is to have the whole cluster -- master included -- be on spot instances. I wonder if that would work well enough for now, granted that you might randomly lose your master. It would definitely be easier and quicker to implement.

**Comment by ericmjonas** [comment]
As a start, I think it's totally reasonable to have all of the instances in a cluster be spot instances. Some of the grad students in the lab might need to change their workflows a little bit, but given the scale at which we use EC2, *not* being able to use spot instances is the far bigger deal-breaker.

**Comment by nchammas** [comment]
Sounds good to me. Go ahead and open a PR and we'll take it from there.
