### ISSUE TITLE
Testing on travis with live aws

### ISSUE THREAD

**Issue by ericmjonas** [nchammas/flintrock#36]
There's the possibility that automated testing with travis could get expensive -- on the other hand, I've personally been tripped up by accidentally committing broken code, and as the project gets more traction I probably won't be the only one. Are there any plans to automate the testing of flintrock against real EC2?

**Comment by nchammas** [comment]
No plans at the moment since, as you suggest, it will be expensive.

Flintrock does have a [`test-integration.sh`](https://github.com/nchammas/flintrock/blob/a1a5a7e8216b61eeaf8f33512c3da2b5142c542d/test-integration.sh) script that developers can run locally to test their changes. I intend to run that myself right before merging in any non-trivial PRs, for example, and you can do that while developing.

I didn't mention it before on #35 since we were still working on the structure of the PR, but at this point I'd say take a crack at adding spot instances tests to `test-integration.sh` as part of the PR.

If Flintrock ever builds up good momentum and gets some funding or donations, I may consider scheduling `test-integration.sh` to run on some kind of automated basis. But for now, that's on contributors to do themselves.
