### ISSUE TITLE
Default invocation on python3 anaconda install fails

### ISSUE THREAD

**Issue by ericmjonas** [nchammas/flintrock#64]
I run flintrock inside a conda environment with python3, so 

```
venv/bin/python3 -Wdefault::DeprecationWarning flintrock.py "$@"
```

fails. Thus, alas, flintrock doesn't work out-of-the-box. Is it possible to instead just call `python3` ?(see https://github.com/nchammas/flintrock/blob/master/flintrock#L3 )

**Comment by nchammas** [comment]
I'm working on packaging Flintrock correctly using setuptools and family as part of #15.

You can just call `python3 flintrock.py` and everything will work the same. The `flintrock` executable is just a handy shortcut.

Does that resolve your issue?

**Comment by broxtronix** [comment]
Since this `flintrock` script is a bash script, would it be possible to check for the existence of a virtualenv, and fall back to running `python3` from the user's environment (via `env python3` or similar) if the user has not set up a `virtualenv`?

I understand the general philosophy behind encouraging `virtualenv` use, but it doesn't fit my workflow and so I will probably continue to edit the `flintrock` shell script to be able to use my default Anaconda Python interpreter.  It's not a huge burden to have to edit this script by hand, but I suspect this is something that will trip up new users who try to clone and run `flintrock` from github.  A quick mod to the script like I've proposed above would help to eliminate this tiny bit of new user friction without compromising much else!

**Comment by nchammas** [comment]
@broxtronix - That would be helpful, though I believe that Bash script will soon go away as part of #15 and be replaced by a [`console_scripts` entry point](https://packaging.python.org/en/latest/distributing/#console-scripts) which enables `pip` to automatically setup the correct executable regardless of platform (OS X, Linux, Windows).

I think that's the "correct" way to setup packages for installation, though I'm still figuring this stuff out myself honestly.

**Comment by nchammas** [comment]
Feel free to make that change, though, as you are right it will help eliminate some friction in the meantime without any cost.

**Comment by nchammas** [comment]
Oh, btw @ericmjonas a quick tip: Hit `y` when you're looking at some file on GitHub and GitHub will update the URL to a permanent reference link. :smile_cat: 

Your current link to `flintrock` will refer to a different line or break if we edit or remove the file.

**Comment by nchammas** [comment]
@ericmjonas @broxtronix - Now that Flintrock 0.1 has been released (yay! :tada:) please let me know if this is still an issue.

I've updated the docs to reflect how Flintrock should be installed. It should be both simpler than before and more "correct", and it should cover both of your use cases.
