### ISSUE TITLE
Properly reconfigure Spark on cluster restart

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#8]
If you stop and then start a Flintrock cluster you need to do a little work to make sure that Spark comes back up correctly.

During cluster launch Spark is installed via class methods. These methods need to be refined a bit to cover this case (and eventually, related cases like adding or removing nodes).

**Comment by broxtronix** [comment]
I took a crack at this as part of #13.  It turned out that this refactor was closely related to #6, so I did them together.  The module refactor is something of a straw-man, but whatever we settle on I believe the start and stop logic now works as it should.

One thing that has not been done yet is any refinements to allow adding or removing of slave nodes on the fly.

**Comment by nchammas** [comment]
I took a more limited approach to solving this in #19.

I'll briefly comment on #13 in relation to our offline conversation.
